# File or Class name: input_val_1.py
# Program author(s): Anuj Dwivedi
# Course number and title: COSC4603 - Computer Theory
# Assignment number and name: Assignment #1 - REGULAR EXPRESSION RECOGNIZER
# Due date: 29th January 2024
# Brief description of the purpose of the program::
# This Python program validates user-input regular expressions for characters {a, b, /, *, (, )} AND
# Accept only those strings that can be generated by the given language grammar.


# the complete code plus readme posted to github
"""Github : https://github.com/ANUJDWIVDI/inputvalidator_assign """

""" Set of Functions S,E,T,F,Q,R,U That denote the given state and if Grammar rules are being followed"""


def S(exp):
    global index
    index = 0
    if not T(exp):
        return False
    if not Q(exp):
        return False
    return index == len(exp)


def E(exp):
    global index
    if not T(exp):
        return False
    if not Q(exp):
        return False
    if index < len(exp) and exp[index] == ')' and index + 1 != len(exp):
        return True
    return False


def T(exp):
    global index
    if index < len(exp) and exp[index] in ('(', 'a', 'b'):
        if not F(exp):
            return False
        if not R(exp):
            return False
        return True
    return False


def F(exp):
    global index
    if index < len(exp) and exp[index] in ('a', 'b'):
        index += 1
        if not U(exp):
            return False
        return True
    elif index < len(exp) and exp[index] == '(':
        index += 1
        if not E(exp):
            return False
        if index < len(exp) and exp[index] == ')':
            index += 1
        else:
            return False
        if not U(exp):
            return False
        return True
    return False


def Q(exp):
    global index
    if index < len(exp) and exp[index] == '|':
        index += 1
        if not T(exp):
            return False
        if not Q(exp):
            return False
        return True
    return True


def R(exp):
    global index
    if index < len(exp) and exp[index] in ('(', 'a', 'b'):
        if not F(exp):
            return False
        if not R(exp):
            return False
        return True
    return True


def U(exp):
    global index
    if index < len(exp) and exp[index] == '*':
        index += 1
        if not U(exp):
            return False
        return True
    return True


""" Follow Up and addition of logic through above functions in below given code """


def valid(char):
    if char in ['a', 'b', '*', '(', ')', '|', '$']:
        return 1
    else:
        return 0


print("Enter a Regular exp! , Type 'exit' to quit: ")

input_strings = []  # A list to store the range of expressions whose validity is to be determined.

while True:
    input_string = input()

    if input_string.lower() == 'exit':
        print("\n----------------- RESULT ----------------------\n")
        print("\n-----VALIDITY ---   |     --------REASON----\n")
        break  # Exit the loop only if user enters the word 'exit'

    input_strings.append(input_string)

flag = 0  # to act as a flag variable to indicate validity of expression
result = ''  # to store the valid or invalid string chain
result2 = ''  # to act as the second line of chain with ^ pointer

for exp in input_strings:
    flag = 0
    result = ''
    result2 = ''

    index = 0
    next_char = exp[0]


    def get_next_char():
        global index, next_char
        if (index + 1) < len(exp):
            index = index + 1
            next_char = exp[index]
        elif (index + 1) == len(exp):
            index += 1
            next_char = '$'


    for x in exp:
        if x != ' ' and x != '\t':
            if valid(x):
                result += x
                result2 += ' '
            else:
                flag = 1
                result += x
                result2 += '^'
        elif x == '\t':
            for y in range(4):
                result += ' '
                result2 += ' '
        else:
            result += ' '
            result2 += ' '


    index = 0  # Resets the index for each input string
    next_char = exp[0]  # Resets the next character for each input string



    if not S(exp):
        print(f"INVALID: {exp}")
        if not result2.isspace():
            print("        ", result2,"\t\t\t Invalid Symbols Used")
        else:
            print("\t\t\t\t\t\tInvalid Due to Incorrect Grammar Use")
    else:
        print(f"VALID: {exp}")

